### ISSUE TITLE
Pick<Todo, never>에 대한 답변을 찾아보았습니다.

### ISSUE THREAD

**Issue by eomsteve** [macjjuni/wanted-pre-onboarding-challenge-fe-ts#1]
[www.typescriptlang.org/docs/handbook/utility-types](https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys)
유틸리티 타입중 `Pick`은 `string`과 `union of string literals` 만 허용되므로 앞에 선언되어 있는 타입이 잘못되어 never타입이 나온거같습니다.
```typescript
export type deleteTodoTagType = (
  param: Pick<Todo, "id" & "tags"> // Error : change to "id" & "tags" 
) => Promise<Todo | undefined>;
```

이걸 고치게 되면... deleteTodoTag 함수에서 tags가 옵셔널 체이닝으로 undefined도 포함되는 타입이므로 타입 가드를 활용해 함수를 한번 더 리팩토링 해야할거 같습니다 !

**Comment by macjjuni** [comment]
### 수정 전

```typescript
export type deleteTodoTagType = (
  param: Pick<Todo, "id" & "tags"> // Error : change to "id" & "tags" 
) => Promise<Todo | undefined>;
```
### 수정 후

```typescript
export interface Tag {
  id: string;
  name: string;
}
export type deleteTodoTagType = (
  param: Pick<Todo, "id"> & { tags: Tag[] }
) => Promise<Todo | undefined>;
```
함수를 안건드리고 undefined 포함하지 않는 방향으로 수정했습니다.
답변 감사드립니다!
